USE tis;

INSERT INTO `tis`.`modalidad` (`codigo`, `nombre`, `descripcion`) VALUES ('1', 'Trabajo Dirigido', 'Consiste en trabajos prácticos evaluados y supervisados en instituciones, empresas públicas o privadas, encargadas de proyectar o implementar obras para lo cual y sobre la base de un temario se proyecta, dirige o fiscaliza bajo la dirección de un supervisor o guía de la institución o empresa, también otro campo de acción es el de verificar las soluciones de problemas específicos, demostrando dominio amplio del tema y capacidad para resolver.');
INSERT INTO `tis`.`modalidad` (`codigo`, `nombre`, `descripcion`) VALUES ('2', 'Proyecto de Grado', 'Es el trabajo de investigación, análisis y diseño de <b>objetos de fin social</b> y que cumple con exigencias de metodología cientifica con profundidad similar al de un proyecto de investigación (tesis).');
INSERT INTO `tis`.`modalidad` (`codigo`, `nombre`, `descripcion`) VALUES ('3', 'Adscripcion', 'Se establece la Adscripción como la incorporación de estudiantes de la UMSS a la realización de actividades en los ámbitos académico, de investigación, interacción, y/o de gestión universitaria. La Adscripción consiste en la realización de un Trabajo Dirigido y/o una práctica profesional supervisada (internado) dentro de la Universidad Mayor de San Simón, que desarrollado dentro del marco de las disposiciones del presente reglamento, habilita al estudiante a presentar como Proyecto Final.<p> Para las Carreras de Informática y Sistemas, se plantea clasificar esta modalidad en dos:<br><ul><li><b>Adscripción a la Catedra,</b> si las actividades a realizar persiguen fines netamente académicos y de investigación enmarcadas en el proceso enseñanza-aprendizaje de las carreras de Informática y Sistemas.</li><li><b>Adscripción,</b> si las actividades a realizar no están enmarcadas en el ámbito de la Adscripción a la Cátedra.</li></ul>');
INSERT INTO `tis`.`modalidad` (`codigo`, `nombre`, `descripcion`) VALUES ('4', 'Proyecto de investigacion', 'Es un trabajo de investigación, que cumple con exigencias de metodología científica, a objeto de conocer y dar respuestas a un problema, planteando alternativas aplicables o proponiendo soluciones prácticas y/o teóricas.');
INSERT INTO `tis`.`modalidad` (`codigo`, `nombre`, `descripcion`) VALUES ('5', 'Excelencia', 'Es una modalidad en donde el estudiante obtiene su titulo directamente debido a su desempeno a lo largo de la carrera.');

INSERT INTO `tis`.`carrera` (`codigo`, `nombre`, `descripcion`, `anios_est`) VALUES ('1', 'Licenciatura en Ingenieria de Sistemas', '', '5');
INSERT INTO `tis`.`carrera` (`codigo`, `nombre`, `descripcion`, `anios_est`) VALUES ('2', 'Licenciatura en Ingenieria Informatica', '', '5');
