USE tis;

INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('1', '299');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('1', '305');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('1', '359');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('1', '372');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('1', '391');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('1', '450');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('1', '452');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('3', '320');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('3', '342');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('3', '375');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('3', '392');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('3', '449');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('3', '454');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('4', '1983');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('5', '325');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('5', '379');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('5', '421');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '300');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '311');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '315');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '319');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '334');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '341');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '343');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '349');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '360');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '364');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '384');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '388');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '393');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '394');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '399');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '402');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '409');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '427');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '431');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '433');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '434');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '435');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '440');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '447');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '469');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '1979');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '1989');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('6', '2542');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('7', '211');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('7', '316');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('7', '318');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('7', '326');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('7', '328');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('7', '336');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('7', '337');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('7', '344');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('7', '346');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('7', '348');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('7', '357');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('7', '378');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('7', '382');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('7', '383');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('7', '400');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('7', '418');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('7', '438');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('7', '459');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('9', '325');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('10', '319');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('10', '379');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('10', '380');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('10', '421');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('11', '310');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('11', '361');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('11', '376');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('11', '389');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('11', '464');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('12', '329');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('12', '340');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('12', '353');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('12', '367');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('12', '369');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('12', '419');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('12', '437');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('12', '443');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('12', '445');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('13', '367');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('13', '380');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('13', '405');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('13', '410');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('13', '411');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '210');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '304');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '311');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '335');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '347');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '362');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '381');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '384');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '388');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '393');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '394');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '399');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '402');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '409');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '423');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '431');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '433');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '434');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '435');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '440');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '447');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '453');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('14', '457');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('16', '352');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('17', '299');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('17', '305');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('17', '308');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('17', '323');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('17', '347');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('17', '372');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('17', '381');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('17', '410');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('18', '450');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('22', '305');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('22', '323');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('22', '3452');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('24', '392');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('25', '351');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('25', '436');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('25', '439');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('25', '454');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('27', '320');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('29', '449');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('34', '257');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('34', '375');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('38', '393');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('44', '343');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('44', '405');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('44', '457');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('51', '316');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('52', '328');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('52', '336');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('52', '418');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('59', '379');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('59', '421');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('61', '379');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('61', '421');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('64', '324');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('71', '306');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('71', '318');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('71', '412');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('72', '408');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('75', '317');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('75', '360');
INSERT INTO `tis`.`areatesis` (`id_area`, `id_tesis`) VALUES ('77', '352');

INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('59', '210');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('332', '211');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('113', '257');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('550', '299');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('171', '300');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('285', '300');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1026', '304');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('3098', '305');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1100', '306');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('764', '308');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1682', '310');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('588', '311');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1937', '315');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('3704', '316');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('217', '317');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1862', '318');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1243', '319');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('3394', '319');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('239', '320');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('768', '323');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('2571', '324');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('2133', '325');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('318', '326');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('3653', '328');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('11', '329');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('2143', '334');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('855', '335');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('3435', '336');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('372', '337');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('414', '340');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('2368', '340');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1834', '341');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1376', '342');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('378', '343');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('749', '344');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1869', '346');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('131', '347');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('153', '347');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('152', '348');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('2660', '349');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('397', '351');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('576', '352');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('192', '353');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('369', '357');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('857', '359');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('100', '360');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('332', '361');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('2134', '362');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('59', '364');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1870', '364');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1579', '367');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('544', '369');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('733', '372');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('2483', '375');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('750', '376');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('2970', '378');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('2758', '379');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('65', '380');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('2467', '381');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('709', '382');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1450', '383');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1064', '384');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('3098', '384');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('127', '388');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('437', '389');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('995', '391');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1679', '392');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('3709', '393');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('442', '394');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1631', '399');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('2193', '399');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('3299', '400');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('348', '402');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('349', '402');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('492', '405');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1175', '408');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('162', '409');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('3049', '410');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('3522', '410');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('3255', '411');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('3240', '412');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('2109', '418');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('610', '419');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1033', '421');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('565', '423');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('3085', '427');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('2118', '431');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('2538', '433');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('848', '434');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('867', '435');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('313', '436');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('82', '437');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('2321', '438');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('394', '439');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('3594', '440');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('843', '443');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('3620', '445');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('2703', '447');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1451', '449');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1063', '450');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('415', '452');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1138', '453');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('2594', '453');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('2974', '454');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1864', '457');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1432', '459');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1116', '464');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('1514', '464');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('795', '469');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('2329', '1979');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('853', '1983');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('506', '1989');
INSERT INTO `tis`.`esttesis` (`cod_alumno`, `cod_tes`) VALUES ('2052', '2542');

INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('6', '211', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('6', '299', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('6', '318', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('6', '337', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('6', '344', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('6', '348', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('6', '431', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('8', '310', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('8', '317', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('8', '341', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('8', '411', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('8', '443', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('9', '315', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('9', '346', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('9', '352', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('12', '305',  '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('12', '308',  '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('12', '335',  '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('12', '347',  '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('12', '349',  '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('12', '391',  '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('12', '400',  '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('12', '419',  '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('12', '423',  '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('12', '436',  '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('12', '440',  '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('12', '443',  '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('12', '449',  '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('12', '450',  '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('12', '452',  '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('12', '453',  '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('12', '457',  '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('12', '469',  '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('12', '1983', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('13', '323', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('13', '427', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('16', '337', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('16', '343', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('16', '402', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('21', '360', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('21', '376', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('26', '359', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('29', '378', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('30', '257', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('30', '334', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('30', '445', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('30', '1989', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('31', '325', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('31', '328', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('31', '336', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('31', '418', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('31', '438', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('42', '340', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('42', '367', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('45', '389', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('46', '300', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('46', '304', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('46', '384', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('48', '361', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('49', '364', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('55', '319', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('62', '311', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('62', '320', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('62', '351', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('62', '357', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('62', '375', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('62', '392', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('62', '433', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('62', '439', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('62', '447', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('62', '454', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('62', '1979', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('62', '2542', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('77', '383', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('77', '412', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('77', '459', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('77', '464', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('96', '394', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('98', '435', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('105', '306', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('105', '329', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('105', '342', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('105', '353', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('105', '362', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('105', '369', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('105', '372', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('105', '380', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('105', '393', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('105', '399', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('105', '405', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('105', '410', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('108', '304', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('111', '316', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('112', '324', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('113', '326', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('113', '382', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('116', '357', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('118', '379', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('118', '421', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('119', '381', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('120', '384', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('122', '388', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('122', '409', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('123', '388', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('123', '406', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('124', '408', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('125', '410', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('128', '434', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('129', '437', '1');
INSERT INTO `tis`.`proftesis` (`cod_prof`, `cod_tes`, `tipo_resp`) VALUES ('221', '1989', '1');